### ISSUE TITLE
Conflict with official C# extension installed, how to set FreeOmnisharp as default?

### ISSUE THREAD

**Issue by ghost** [muhammadsammy/free-omnisharp-vscode#10]
Some extensions like C# snippets require the official ``ms-dotnettools`` version of C# extension to be installed and enabled. 

**If I have both Official C# and FreeOmnisharp C# extensions, how do you set in ``launch.json`` which one to use for debugging?** When I press F5 it uses the official one to run the debugger not this one.

A lot of popular extensions depend on the official one.

## Environment data
`dotnet --info` output: .NET 5.0.102 SDK Installed
VS Code version: Latest
C# Extension version: Latest

## Steps to reproduce
1. Install the Microsoft Official C# extension for VS Code
2. Install the Free Omnisharp VSCode Extension
3. Run the program, uses official MS C# by default

## Expected  behavior
* Be able to set the default extension to use as FreeOmnisharp
* OR
* Allow third-party extensions to think Microsoft Official C# is installed

## Actual behavior
* Debugger runs with official c# extension not with FreeOmnisharp
* Disabling or removing microsoft C# extension makes it impossible to use other extenions that depend on it.

**Comment by muhammadsammy** [comment]
I don't know if vscode can choose one to be the default or not.
But you can change the C# key inside the `extensionDependencies` key of `package.json` of an extension source from `ms-dotnettools.csharp` to `muhammad-sammy.csharp` and build that extension's vsix file from source. 

Or you can change all occurrences of `ms-dotnettools.csharp` in an installed extension in `.vsixmanifest` and `package.json` files at `$HOME/.vscode-oss/extensions/EXTENSION_FOLDER/` and do this for every update for that extension.

---

Another solution would be to build `free-omnisharp-vscode` extension [from source](https://github.com/muhammadsammy/free-omnisharp-vscode#build-from-source) **but** change the extension id before building at:

https://github.com/muhammadsammy/free-omnisharp-vscode/blob/f0ec1d43becef701c43b9587463e28a95e70b33f/src/constants/CSharpExtensionId.ts#L6

and at
https://github.com/muhammadsammy/free-omnisharp-vscode/blob/f0ec1d43becef701c43b9587463e28a95e70b33f/package.json#L3

**Comment by bachmannn** [comment]
> I don't know if vscode can choose one to be the default or not.

There is a property in `launch.json` for `"type": "coreclr"` that directly calls the `C#` extension. Is it defined in the addon somewhere, which could be easily replaced with `"type": "free-coreclr"` so it calls this extension instead of default for `coreclr`?

**Comment by muhammadsammy** [comment]
I believe it's defined in

https://github.com/muhammadsammy/free-omnisharp-vscode/blob/9d4a5919c1d3707ca2b7e134e1abdad8630d2c82/src/omnisharp/extension.ts#L206

and in

https://github.com/muhammadsammy/free-omnisharp-vscode/blob/9d4a5919c1d3707ca2b7e134e1abdad8630d2c82/package.json#L1004

**Comment by pm4rcin** [comment]
It has improved in the meantime. For example Roslynator supports our version and also it should be reported to the upstream repositories if they depend on official C# extension. Let's close that one.
