### ISSUE TITLE
Problem with debugging C# project via netcoredbg

### ISSUE THREAD

**Issue by pm4rcin** [muhammadsammy/free-omnisharp-vscode#2]
## Environment data
`dotnet --info` output: dotnet --info
Zestaw .NET Core SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   3.1.108
 Commit:    c423b556b5

Środowisko uruchomieniowe:
 OS Name:     arch
 OS Version:  5.8.13.arch1-1
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.108/

Host (useful for support):
  Version: 3.1.8
  Commit:  05a0c8f6b1

.NET Core SDKs installed:
  3.1.108 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version: 1.49.3
C# Extension version: 1.23.2

## Steps to reproduce
1. Set breakpoint
2. Click debug the project with following launch.json file:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp3.1/First.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "pipeTransport": {
                "pipeCwd": "${workspaceFolder}",
                "pipeProgram": "bash",
                "pipeArgs": [],
                "debuggerPath": "/usr/bin/netcoredbg"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

## Expected  behavior
The debugging should start normally and stop at given point.

## Actual behavior
There's a popup which says "Couldn't find a debug adapter descriptor for debug type 'coreclr' (extensions might have failed to activate)" and all I can do is click cancel or edit the launch.json file.

**Comment by muhammadsammy** [comment]
This happens because this extension does not download the `vsdbg-ui` which is bundled with the `vsdbg` debugger and also does not activate debuggers https://github.com/muhammadsammy/free-omnisharp-vscode/blob/master/src/coreclr-debug/activate.ts#L19. this is to avoid the proprietary licensed parts of Microsoft's extension.

I'm not aware of any alternatives or how to make it work without the non-free stuff, so any help is welcome!

**Comment by muhammadsammy** [comment]
`netcoredbg` is now integerated with this extension and works out of the box thanks to @jamsilva (#4).
