### ISSUE TITLE
Extension fails to download latest version of debugger

### ISSUE THREAD

**Issue by iamtoaster** [muhammadsammy/free-omnisharp-vscode#20]
## Issue Description ##
As the title says, the extension fails to download the latest version of samsung debugger. From what I can see, it is because they changed how the release archives are labeled.
## Steps to Reproduce ##
Install extension and let it try to download dependencies.
## Expected Behavior ##
Successful installation
## Actual Behavior ##
Installation fails because the file requested by the extension does not exist.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.204
 Commit:    84d1fe1bb7

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.204/

Host (useful for support):
  Version: 5.0.7
  Commit:  a002cbfb6b

.NET SDKs installed:
  5.0.204 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|muhammad-sammy|1.23.12|
|csharpextensions|jsw|1.4.0|;

</details>

**Comment by muhammadsammy** [comment]
Please install the extension artifact from the latest CI build here: https://github.com/muhammadsammy/free-omnisharp-vscode/runs/2984711477

I will release the extension with this fix to OpenVSX once a new omnisharp-vscode release gets published

**Comment by muhammadsammy** [comment]
Published to OpenVSX with the fix
