### ISSUE TITLE
Publishing extension workflow is not working

### ISSUE THREAD

**Issue by muhammadsammy** [muhammadsammy/free-omnisharp-vscode#21]
https://github.com/muhammadsammy/free-omnisharp-vscode/actions/runs/1027459863

https://github.com/muhammadsammy/free-omnisharp-vscode/blob/860834fb7abfa76047a8a9a8a40c3a5422f9ca30/.github/workflows/publish.yml

**Comment by pm4rcin** [comment]
@muhammadsammy the logs aren't available so it's not possible to troubleshoot.

**Comment by muhammadsammy** [comment]
I will update the extension and new logs will be available and I will share them here

**Comment by muhammadsammy** [comment]
https://github.com/muhammadsammy/free-omnisharp-vscode/runs/4912860620?check_suite_focus=true
the error that happens now is different from the one before, the problem was the ci cannot find the vsix file to upload to OpenVSX on this step:
https://github.com/muhammadsammy/free-omnisharp-vscode/blob/f213efc9ead4357997f59ebe123c768482766043/.github/workflows/publish.yml#L25

**Comment by pm4rcin** [comment]
I think it's because release-ci job was not completed before publish.

**Comment by muhammadsammy** [comment]
just tried re-run the action, still the same error

**Comment by pm4rcin** [comment]
Oh and one more thing. Upstream uses [NodeJS 15](https://github.com/OmniSharp/omnisharp-vscode/blob/752a56a7a079beeeb5bc36860a4b1fa0b659fabb/.github/workflows/release-ci.yml#L17) so I guess we should update?

**Comment by muhammadsammy** [comment]
That eleminated the error https://github.com/muhammadsammy/free-omnisharp-vscode/runs/4913046575?check_suite_focus=true
I will change the access token and try again

**Comment by muhammadsammy** [comment]
I think it seems to be fixed. the error from ovsx in the old logs was ` no such file or directory` but now it is ` extension is already published`
https://github.com/muhammadsammy/free-omnisharp-vscode/runs/4913072637?check_suite_focus=true#step:8:7
Or should we try to bump version and try to actually publish the extension?

**Comment by pm4rcin** [comment]
That's strange. If you didn't manually upload to open-vsx then I don't know how it was uploaded. Or did you? Because VSCodium showed an update and looks like it worked. I haven't tested too much but that https://github.com/OmniSharp/omnisharp-vscode/pull/4948/files works which was added with 1.24 release.

**Comment by pm4rcin** [comment]
Or it was automatically found by open-vsx. Maybe they have some bot which scans once in a while for new release?

**Comment by muhammadsammy** [comment]
Oh yes I've uploaded it manually just after I merged changes from upstream.

**Comment by muhammadsammy** [comment]
> Or it was automatically found by open-vsx. Maybe they have some bot which scans once in a while for new release?

yes, they have a bot that does this, but not for this repo, I think it's for extensions with no OpenVSX account

**Comment by pm4rcin** [comment]
I also see that they have changed how they [package](https://github.com/OmniSharp/omnisharp-vscode/commit/b43193c31ecf1457c7a3d0e14e2913261fd0c1eb) the extension. I think that it won't be hard to add because that [action](https://github.com/muhammadsammy/free-omnisharp-vscode/runs/4912975891?check_suite_focus=true) was successfull. It's probably good idea to pull that changes and bump version like we did before with -PATCH and see if everything works.

**Comment by muhammadsammy** [comment]
I've tried to pump version, change the gulp command and it was published successfully to OpenVSX: https://github.com/muhammadsammy/free-omnisharp-vscode/runs/4922065591?check_suite_focus=true#step:8:6 

I do not know why the vsix file was not being detected before, but it works now
Thanks a lot, @pm4rcin!

**Comment by pm4rcin** [comment]
Great to see it's working! One thing to note is that we should track progress on https://github.com/eclipse/openvsx/issues/336 and make changes to workflows when new release of Omnisharp arrives.

**Comment by pm4rcin** [comment]
@muhammadsammy open-vsx has merged the platform-specific PR. I think it'd be a good idea to edit CI and check now if it builds before new version of extension is released in the future.

**Comment by muhammadsammy** [comment]
The release-ci already creates platform-specific vsix files, but we need to modify [publish ci](https://github.com/muhammadsammy/free-omnisharp-vscode/blob/master/.github/workflows/publish.yml) to publish multiple platform specific versions

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
y0ht0nka, @rahalio, @zhuantouer, @Tulune4ka91, @jarirajari, @KassUA, @broerjuang, @ochi51, @igorroder, @jogyfelix, @junyitian, @CMD-reverse, @IMRFeng, @TheArtOfPour, @hsrg70, @RicoToothless, @getspooky, @jaschadub, @kmazz, @fucbill, @elnegrogato, @jesterfunk, @somaliz, @cauchywei, @isfang, @amitchoubey14, @Lance-N3rdlov3, @cetfu, @xingheng, @korteke, @tenerecodes, @EtemenNiguru, @YankeeZulu, @douglasjunior, @martincalveira, @zhouhuan666, @HungNguyenBao, @kid1carus, @QuincyGann, @vsrole, @sindyyo, @Meeshbhoombah, @raghavendra-udyavar, @gc87, @manjula-dube, @robgering, @scriptsman, @shivekkhurana, @hswick, @pickupsbzqhxuyuan, @skensell, @zhyuanad, @99ashutosh, @jkxyz, @dec0dOS, @jesterfunk, @thinalai, @zhuantouer, @nguyenvo1292, @ggsonic, @bbeale, @MisterReally, @ACiep, @yhuag, @acefsm, @devSC, @hswick, @8adre, @siyavash4812, @shashiks, @igorroder, @tiancheng91, @rayyee, @jck-blck, @vpodolyan, @applejian, @alittlecodebox, @RFG-G, @cassidysoreal, @anealo, @tcfkaj, @fevrin, @vitvly, @seipy, @dillchen, @bbarcesaj125, @lbritney, @codedplanetuk, @itsstdev, @Ewkoll, @bitruss, @LeeDongHyeok, @melusi-k, @maxmousee, @LeafarDev, @fengmm521, @benzumbrunn, @abc0xmattyic333, @gourav-singhalloganfreeman, @dorucioclea, @denisson, @Qs8xZaXD3o, @alittlecodebox, @marcusrbrown, @seanuefa, @SDPyle, @getspooky, @bbeale, @awkward-minion, @RockmanR, @aspasia, @huap, @HAOYUatHZ, @jeffersonnnn, @hymnfish, @KyleNie, @HoogvlietsR, @saltb0rn, @0xErick, @hackerGA17, @YankeeZulu, @mailaneel, @bigbuffetboy420, @jacobc-eth, @dehli, @youngshingjun, @huixisheng, @Suburbanno, @LoicMahieu, @BrendanLouis1223, @nguyenvo1292, @firevenus, @henryhawke, @sheluchin, @smarthomecode, @vpodolyan, @That1bull-BK, @vasylnahuliak, @carlfairclough, @eltonlaw, @totmann, @scriptsman, @enriqueruiz, @marcofaggian, @lukaszfryc, @Pryority, @zqhxuyuan, @thejoven
