### ISSUE TITLE
Extension cannot be installed

### ISSUE THREAD

**Issue by vickyorlo** [muhammadsammy/free-omnisharp-vscode#25]
As it stands right now, the extension cannot be installed. The reason is quite simple - it tries to download netcoredbg from https://github.com/Samsung/netcoredbg/releases/download/1.2.0-825/netcoredbg-linux-amd64.tar.gz , but the file actually got replaced and the correct URL is now https://github.com/Samsung/netcoredbg/releases/download/1.2.0-825/netcoredbg-linux-amd64_fixed.tar.gz

**Comment by dunnry** [comment]
Yes, this is breaking gitpod and anyone that tries to use extension.  Would love for the PR (#24) to get merged

**Comment by BUYT-1** [comment]
Quick and dirty fix for now:
`sed -i 's:/netcoredbg-linux-amd64:&_fixed:' package.json`
(do this in the cloned repo directory)

**Comment by muhammadsammy** [comment]
#24 was merged and I released `1.23.15-PATCH` to OpenVSX
You may need to choose the version manually:
![image](https://user-images.githubusercontent.com/35064832/133830382-856bee28-a921-48ed-b94f-0d43666677a3.png)

**Comment by NelsonAPenn** [comment]
I know this issue has been closed, but installing another version is not working for me. Whenever I select the 1.23.15-PATCH release, it resets my installation to version 1.23.15. Does anyone else get this?

OS - Ubuntu 20.04, IDE: VSCodium 1.60.2

**Comment by muhammadsammy** [comment]
Hello, @NelsonAPenn!
A workaround to this behavior is disabling extension updates in vscodium's settings.json:
`"extensions.autoUpdate": false,`
and then install the `PATCH` version

**Comment by NelsonAPenn** [comment]
Thanks for your prompt response! This works, thank you for the help.
