### ISSUE TITLE
Release the latest version

### ISSUE THREAD

**Issue by purkhusid** [muhammadsammy/free-omnisharp-vscode#26]
Would it be possible to push a new release to OpenVSX with the fix that was added here: https://github.com/muhammadsammy/free-omnisharp-vscode/pull/24 ?

**Comment by purkhusid** [comment]
Nevermind, I just saw that it was pushed with the PATCH postfix.

**Comment by hm2075** [comment]
Patch version isn't visible in gitpod,  could you upload a new release instead of a patch?

Current vscode image is 1.57  and latest in nightly is higher
