### ISSUE TITLE
Report issue should not send issues to https://github.com/OmniSharp/omnisharp-vscode/

### ISSUE THREAD

**Issue by gregg-miskelly** [muhammadsammy/free-omnisharp-vscode#29]
Hello, I help support the official Microsoft C# extension. We have now received a few issues from this extension, and it would be helpful to us if you made changes to make this process better. Please consider either changing [this line](https://github.com/muhammadsammy/free-omnisharp-vscode/blob/1fc22c4ae52f900b2e46178f93de4ee2028e84a2/src/features/reportIssue.ts#L15) to report the issue here, or at least change the body of the issue in an obvious way to indicate that a fork of the extension was used.

Thanks!

**Comment by muhammadsammy** [comment]
Hello! Sure thing :+1:

**Comment by muhammadsammy** [comment]
Hello! 
Sure. I will change them :+1:
