### ISSUE TITLE
Is the runtime license change legal?

### ISSUE THREAD

**Issue by spoenemann** [muhammadsammy/free-omnisharp-vscode#3]
In https://github.com/muhammadsammy/free-omnisharp-vscode/commit/6890051d34fad7a413eedbcef3470aa586d5f115 you changed the runtime license from [Microsoft's proprietary license](https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt) to MIT / Apache-2.0. @muhammadsammy are you sure you are allowed to do this?

The [License section](https://github.com/OmniSharp/omnisharp-vscode#license) in the original README states

> The Microsoft C# extension is subject to [these license terms](https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt).

**Comment by muhammadsammy** [comment]
I've removed the "Debugger" `runtimeDependency` which have a proprietary license here: [3d32a99](https://github.com/muhammadsammy/free-omnisharp-vscode/commit/3d32a994bdf284377e95b675806b3b0534aee334#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L251-L303).
This extension have "Razor" ([Apache-2.0](https://github.com/OmniSharp/omnisharp-vscode/issues/3894#issuecomment-657960782)) and "Omnisharp" (MIT) runtime dependencies only and the source code for the original repo is [MIT](https://github.com/OmniSharp/omnisharp-vscode/blob/master/LICENSE.txt), so as far as I know, it's ok to remove the proprietary license.

**Comment by spoenemann** [comment]
For [vscode](https://github.com/microsoft/vscode) there is a [Wiki page](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code) explaining the difference between the MIT licensed source and the proprietary distribution. It would be nice to have a similarly clear statement about [omnisharp-vscode](https://github.com/OmniSharp/omnisharp-vscode) by its maintainers.

But if you are sufficiently confident about the license change, feel free to close this issue.

**Comment by spoenemann** [comment]
@muhammadsammy the license change was effective since version 1.23.2, right? I'd like to delete the previous versions with the proprietary license from open-vsx.org, since they cannot be used from VSCodium and other non-Microsoft clients.

**Comment by muhammadsammy** [comment]
@spoenemann Sure! versions prior to 1.23.2 does have the proprietary license.

**Comment by spoenemann** [comment]
Ok, I deleted the older versions.
