### ISSUE TITLE
Support for .NET 7

### ISSUE THREAD

**Issue by Kaoticz** [muhammadsammy/free-omnisharp-vscode#43]
## Is your feature request related to a problem? Please describe.
The extension currently doesn't work with .NET 7 tooling. This is a problem because it prevents me from working with projects that target .NET 7.

## Describe the solution you would like
I want the extension to be functional when only .NET 7 runtime and SDK are installed in the system.

## Describe alternatives you've considered
The extension works when .NET 6 tooling is installed, but only with projects that also target .NET 6 or lower.

## Additional context
This is the message Omnisharp logs when trying to start:
```
Starting OmniSharp server at 11/23/2022, 12:57:15 PM
    Target: /home/user/Documents/Programming/Repositories/SomeProject/SomeProject.sln

OmniSharp server started with .NET 7.0.100
.
    Path: /home/user/.vscode-oss/extensions/muhammad-sammy.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll
    PID: 78795

You must install or update .NET to run this application.

App: /home/user/.vscode-oss/extensions/muhammad-sammy.csharp-1.24.0/.omnisharp/1.38.0-net6.0/OmniSharp.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=arch-x64
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
- Arch Linux
- VSCodium 1.73.1.22314-1

**Comment by pm4rcin** [comment]
You have to update your extension. From the folder it looks like you have version 1.24. I have 1.25 and it works without problems. I have VSCodium installed as flatpak.

**Comment by Kaoticz** [comment]
For some reason the updated version wasn't showing for me in the marketplace. I had to download the extension directly from [open-vsx](https://open-vsx.org/extension/muhammad-sammy/csharp) and install it manually.

**Comment by pm4rcin** [comment]
If the problem was resolved please close bug report.
