### ISSUE TITLE
Update to upstream 1.25.4 to fix Razor Language Server startup issue

### ISSUE THREAD

**Issue by RealYHD** [muhammadsammy/free-omnisharp-vscode#47]
Hi, kindly requesting an update to the latest upstream release of the extension (1.25.4). It fixes an issue where the Razor Language Server will not start with OpenSSL 3 (described here [dotnet/runtime#67375](https://github.com/dotnet/runtime/issues/67375)).  According to [dotnet/razor#6241](https://github.com/dotnet/razor/issues/6241), this issue is fixed in the [latest release](https://github.com/dotnet/razor/issues/6241#issuecomment-1402517113).

Thanks for your work!

**Comment by petrechitashvili** [comment]
https://github.com/muhammadsammy/free-omnisharp-vscode/issues/44

**Comment by muhammadsammy** [comment]
upgraded to https://github.com/muhammadsammy/free-omnisharp-vscode/releases/tag/1.25.7 and published to openvsx

**Comment by petre-c** [comment]
Thank you very much 🙏

**Comment by muhammadsammy** [comment]
My pleasure.
