### ISSUE TITLE
Publish latest version of extension to open-vsx

### ISSUE THREAD

**Issue by pm4rcin** [muhammadsammy/free-omnisharp-vscode#57]
@muhammadsammy because CI was not working before your corrections, the tag was created but it doesn't have any artifacts and it was not pushed to open-vsx. Could you re-trigger it to make it into the store?

**Comment by muhammadsammy** [comment]
Done. Here: https://github.com/muhammadsammy/free-omnisharp-vscode/actions/runs/6064031733 and https://github.com/muhammadsammy/free-omnisharp-vscode/actions/runs/6064031736
